[package]
name = "kate"
license-file = "LICENSE"
documentation = "https://amy.is-a.dev/kate"
repository = "https://github.com/nullishamy/kate/"
version = "0.1.0"
readme = "README.md"
description = "A WIP JVM written in rust."
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
bitflags = "1.3"
paste = "1.0.6"
anyhow = "1.0.56"
thiserror = "1.0.30"
enum-as-inner = "0.4.0"
clap = { version = "3.1.6", features = ["derive"] }
tracing = "0.1.32"
tracing-subscriber = "0.3.9"
tui = "0.17"
crossterm = { version = "0.22", features = ["event-stream"]}
parking_lot = "0.12.0"
lazy_static = "1.4.0"
tokio = { version = "1.17.0", features = ["full"] }
tokio-stream = "0.1.7"
