on:
    push:
        tags:
            - "v*"

jobs:
    docgen:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout docs branch
              uses: actions/checkout@v3

            - name: Install latest stable rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  default: true
                  override: true

            - name: Delete existing docs directory
              run: rm -rf ./docs/

            - name: Generate docs
              run: cargo doc --release --no-deps

            - name: Create index.html for github pages
              run: echo "<meta http-equiv=\"refresh\" content=\"0; url=Kate\">" > target/doc/index.html

            - name: Copy generated docs to docs folder
              run: cp -r ./target/doc ./docs

            - name: Commit updated documentation
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "docs: autogenerate documentation"
