on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install latest nightly rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

      - name: Delete existing docs directory
        run: rm -rf ./docs/

      - name: Generate docs
        run: cargo doc --release --no-deps

      - name: Create index.html for github pages
        run: echo "<meta http-equiv=\"refresh\" content=\"0; url=cli\">" > target/doc/index.html

      - name: Create .nojekyll to stop Jekyll builds
        run: echo "." > target/doc/.nojekyll

      - name: Copy generated docs to docs folder
        run: cp -r ./target/doc ./docs

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: docs
          clean: true
