name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  release-amd64:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest stable rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --release --bins

      - name: Rename executable (linux)
        run: mv target/release/kate target/release/kate-linux-amd64
        if: matrix.os == 'ubuntu-latest'

      - name: Rename executable (mac)
        run: mv target/release/kate target/release/kate-darwin-amd64
        if: matrix.os == 'macos-latest'

      - name: Rename executable (windows)
        run: Rename-Item .\target\release\kate.exe kate-win32-amd64.exe
        if: matrix.os == 'windows-latest'

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/kate*64?(.exe)
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-darwin-aarch64:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest stable rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          default: true
          override: true

      - name: Build
        run: cargo build --release --bins --target aarch64-apple-darwin

      - name: Rename executable
        run: mv target/aarch64-apple-darwin/release/kate target/aarch64-apple-darwin/release/kate-darwin-aarch64

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: target/aarch64-apple-darwin/release/kate*64?(.exe)
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
